apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x89om299w-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x89om299w-nodejs 
  name: x89om299w-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: x89om299w-nodejs 
